Accept column names in `TSx.describe()`.
xKDR/TSx.jl pull request #65
Opened 2022-09-06 13:23 UTC by codetalker7

This PR solves https://github.com/xKDR/TSx.jl/issues/50. I've added two additional arguments in `TSx.describe`:

- A keyword argument `cols`, used to specify for which column the summary is to be printed.
- `stats`, to specify what summary stats to print.

So now, one can do something like (please see the docstring for the whole code)

```julia
describe(ts, cols=:Index)
describe(ts, :min, :max, cols=:x1)
```

2022-09-06 13:27 UTC, codetalker7 commented
It seems like I'll have to change a relevant test as well.

2022-09-07 12:24 UTC, chiraganand requested changes

2022-09-07 12:24 UTC, chiraganand commented on src/utils.jl
> +   1 │ x1            2      4
Can you add `stats` keyword documentation? The text above the examples should mention this.

Examples showing it's usage would be good. Perhaps, also refer: https://dataframes.juliadata.org/stable/lib/functions/#DataAPI.describe for list of supported actions but we should show a few examples at least.

2022-09-10 09:11 UTC, codetalker7 commented on src/utils.jl
> +   1 │ x1            2      4
Added the documentation for the keywords. I've also added all the relevant examples, and referred to the DataFrames.jl docs for more details.

2022-09-10 10:16 UTC, chiraganand approved these changes

2022-09-10 10:16 UTC, merged