Fixing `getindex` tests.
xKDR/TSx.jl pull request #69
Opened 2022-09-08 13:20 UTC by codetalker7

This PR is mainly to solve https://github.com/xKDR/TSx.jl/issues/63. A minor change has been made in the code for `getindex(::TS, ::Year, ::Month)`. Also, many testcases in `tests/getindex.jl` were faulty, which have now been fixed.

It should be noted that even though the tests for `getindex` are fixed, there are still erroneous tests in the package (as can be seen from the CI log).

2022-09-08 18:00 UTC, codetalker7 commented
Also added the `StatsBase` test dependency which seemed to be used (`sample` function in `tests/utils.jl`); now all the tests are passing.

2022-09-09 12:34 UTC, chiraganand requested changes

2022-09-09 12:34 UTC, chiraganand commented on Project.toml
> +StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
This is non-PR specific change. Can you remove this?

2022-09-09 12:34 UTC, chiraganand commented on Project.toml
> +julia = "1.7"
Non-PR specific change.

2022-09-09 12:34 UTC, chiraganand commented on test/runtests.jl
> +using StatsBase
Non-PR specific change.

2022-09-09 12:34 UTC, chiraganand commented
> Also added the `StatsBase` test dependency which seemed to be used (`sample` function in `tests/utils.jl`); now all the tests are passing.

Just read this. You can ignore my comments of non-PR specific changes.

2022-09-09 12:35 UTC, chiraganand approved these changes

2022-09-09 12:35 UTC, merged