Implement `Tables.jl` interfaces.
xKDR/TSx.jl pull request #80
Opened 2022-10-06 05:30 UTC by codetalker7

This PR is to solve https://github.com/xKDR/TSx.jl/issues/23. Many `Tables.jl` functions have been implemented, and the work is delegated to `DataFrames.jl`. For reference, we have implemented the functions that `DataFrames.jl` does in their code: https://github.com/JuliaData/DataFrames.jl/blob/main/src/other/tables.jl.

I'm assuming we don't need to test this, because `DataFrames.jl` is already testing their implementation of these interfaces. Also, since this won't be directly used by users of the package, I'm assuming we don't have to add documentation either.

2022-10-08 06:43 UTC, chiraganand commented
> I'm assuming we don't need to test this, because `DataFrames.jl` is already testing their implementation of these interfaces. Also, since this won't be directly used by users of the package, I'm assuming we don't have to add documentation either.

In my opinion, we would need both test cases and documentation. The package needs test cases so that if something in Tables.jl changes in the future which changes DF implementation then our test cases should break, no other way to know if something has changed upstream.

A basic documentation page is required to tell users that the package complies with Tables.jl interfaces and can be used to port data to other table formats.

2022-10-09 11:03 UTC, codetalker7 commented
@chiraganand I compiled three examples of converting a `TS` object to other tabular formats via our `Tables.jl` implementation.

```julia
using TSx, TimeSeries, Dates, DataFrames, CSV;
dates = Date(2018, 1, 1):Day(1):Date(2018, 12, 31)
ts = TS(DataFrame(Index = dates, x1 = 1:365))

# conversion to DataFrame
df = DataFrame(ts)

# conversion to TimeArray
timeArray = TimeArray(ts, timestamp = :Index)

# writing to CSV
CSV.write("ts.csv", ts)
```

So our `Tables.jl` interfaces are working well. Next I believe we should write a constructor for `TS` which works on any type that implements `Tables.jl` interfaces (and not separate constructors for `DataFrame`, `CSV` etc.)

2022-10-09 18:45 UTC, codetalker7 commented
I've also modified the constructor so that it works on a general `Tables.jl` compatible table. The idea is simple: first convert to a `DataFrame`, and then to a `TS` object. For instance, the following conversions are now working smoothly.

```julia
using TSx, DataFrames, CSV, TimeSeries, Dates

# converting DataFrame to TS
ts = TS(DataFrame(Index=1:10, x1=1:10))

# converting from TimeArray to TS
dates = Date(2018, 1, 1):Day(1):Date(2018, 12, 31)
ta = TimeArray(dates, rand(length(dates)))
ts = TS(ta)

# converting from CSV to TS
ts = CSV.read("filename.csv", TS)

```

The next step in this PR will be to add all this to the documentation, and add some tests.

2022-10-13 07:06 UTC, chiraganand commented on src/TS.jl
> +    coredata = DataFrame(table, copycols=true)
Can you measure if there is any performance impact of this versus when you directly supply a `DataFrame` to `TS` constructor?

2022-10-13 07:08 UTC, chiraganand commented
> I've also modified the constructor so that it works on a general `Tables.jl` compatible table. The idea is simple: first convert to a `DataFrame`, and then to a `TS` object. For instance, the following conversions are now working smoothly.
> 
> ```julia
> using TSx, DataFrames, CSV, TimeSeries, Dates
> 
> # converting DataFrame to TS
> ts = TS(DataFrame(Index=1:10, x1=1:10))
> 
> # converting from TimeArray to TS
> dates = Date(2018, 1, 1):Day(1):Date(2018, 12, 31)
> ta = TimeArray(dates, rand(length(dates)))
> ts = TS(ta)
> 
> # converting from CSV to TS
> ts = CSV.read("filename.csv", TS)
> ```
> 
> The next step in this PR will be to add all this to the documentation, and add some tests.

This looks good. It might be worth mentioning in the documentation that the table object will first get copied into a `DataFrame` and then into a `TS` object.

2022-10-14 07:21 UTC, codetalker7 commented
Hi @chiraganand I'm not sure about what exactly we need to test here. Could you give an idea? Should I just write test cases which check if the code executes without errors?

2022-10-15 05:51 UTC, chiraganand commented
> Hi @chiraganand I'm not sure about what exactly we need to test here. Could you give an idea? Should I just write test cases which check if the code executes without errors?

I think at least one or two test cases for each method we have implemented which just checks the output with a constant object should do. For example, the conversion from a constant pre-defined `ta = TimeArray(...)` using `TS(ta)` should match and similarly for other methods.

2022-10-15 05:53 UTC, chiraganand requested changes
Can you update README.md and docs/demo_finance.md to use `MarketData.yahoo()` function to create `TS` objects? This will also resolve concerns raised in #64.

2022-10-16 10:50 UTC, chiraganand requested changes
For testing Tables.jl interfaces see: https://tables.juliadata.org/stable/#Testing-Tables.jl-Implementations

2022-10-16 10:50 UTC, chiraganand commented on test/tables.jl
> +for i in 1:15
Can you use `nrow(ts)` instead of constant `15` so that it is easier to modify the test data later?

2022-10-16 10:50 UTC, chiraganand commented on test/tables.jl
> +    @test day(row[:Index]) == row[:x1]
Can you make the LHS and RHS independent of each other? Let us not use the same `row` value in both LHS and RHS.

2022-10-16 10:50 UTC, chiraganand commented on test/tables.jl
> +for col in Tables.columns(ts)
Here, I think we should test the values returned by `Tables.columns(ts)` iterator with the actual column values in `ts`. Matching the number of rows is not needed here.

2022-10-17 11:08 UTC, chiraganand commented on docs/src/demo_finance.md
> +DataFrames.rename!(ibm_aapl.coredata, [:Index, :IBM, :AAPL]) # rename the columns using DataFrame API (making sure `Index` is the first col)
Can you use `TSx.rename!()` here?

2022-10-17 12:08 UTC, chiraganand approved these changes

2022-10-17 12:26 UTC, merged